services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: ringle-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ringle
      MYSQL_USER: ringle
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      ringle-network:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: ringle-redis
    ports:
      - "6378:6379"
    networks:
      ringle-network:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    image: jihoonyc/ringle-app:latest
    container_name: ringle-spring
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      ringle-network:

networks:
  ringle-network:
    driver: bridge