services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: ringle-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ringle
      MYSQL_USER: ringle
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      ringle-network:

  redis:
    image: redis:latest
    container_name: ringle-redis
    ports:
      - "6378:6379"
    networks:
      - ringle-network

networks:
  ringle-network:
    driver: bridge