server:
  port: 8080

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ringle-mysql:3306/ringle?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: ringle
    password: 1234
    hikari:
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ringle-redis
      port: 6379

# JWT
jwt:
  issuer: ringle@spring.security.com
  access_expiration: 86400000  # 1 day
  secret-key: ringle-assignment-secret-key-for-hmac-sha256-token
